name: "Webhook Trust Gate (Enterprise)"
description: "A GitHub Action to securely verify Stripe & Razorpay webhooks and maintain an immutable ledger of events."
author: "kklabsinfo-del"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  provider:
    description: "Webhook provider (stripe or razorpay)"
    required: true
  payload:
    description: "Raw webhook JSON payload"
    required: true
  signature:
    description: "Webhook signature header"
    required: true
  secret:
    description: "Webhook secret (from Stripe or Razorpay)"
    required: true
  ledger_branch:
    description: "Git branch to store the ledger"
    required: false
    default: "webhook-ledger"
