name: "Webhook Trust Gate"
description: "Verified, deduplicated, auditable webhook processing for Stripe & Razorpay with tamper-evident Git ledger"
author: "your-github-username"

branding:
  icon: "shield"
  color: "blue"

inputs:
  provider:
    description: "Webhook provider (stripe or razorpay)"
    required: true
  payload:
    description: "Raw webhook JSON payload"
    required: true
  signature:
    description: "Webhook signature header"
    required: true
  secret:
    description: "Webhook secret (from provider)"
    required: true
  ledger_branch:
    description: "Git branch to store the ledger"
    required: false
    default: "webhook-ledger"
  skip_signature:
    description: "Skip signature verification (for local testing)"
    required: false
    default: "false"

outputs:
  event_id:
    description: "Provider-native unique event ID"
  event_hash:
    description: "SHA-256 hash of normalized event"
  normalized_event:
    description: "JSON of the normalized event"

runs:
  using: "node20"
  main: "dist/index.js"